Follow speed limits for slotcar robots
open-rmf/rmf_simulation pull request #56
Opened 2021-10-11 09:15 UTC by luca-della-vedova

## New feature implementation

### Implemented feature

This PR allows simulated robots to respect speed limits specified in path requests, requires https://github.com/open-rmf/rmf_internal_msgs/pull/28 and https://github.com/open-rmf/rmf_ros2/pull/132

### Implementation description

A new `std::optional<double> max_speed` is added to `UpdateResult` in `slotcar_common`, if a speed limit was specified in the message (specifically if it was > 0.0) the minimum between vehicle nominal speed and speed limit will be the navigation speed of the vehicle, before it was fixed at being the maximum robot speed at all times.

Since we need to store more information than a simple pose for differential drive robots' trajectories (i.e. speed limit), a new struct `DiffDriveTrajectory` was added and a minor refactoring took place to use it throughout the code.

2021-11-24 06:41 UTC, aaronchongth requested changes
Thanks for adding this feature, @luca-della-vedova! I've taken a quick look, other than the comments, I also feel that we should revisit functions like `calculate_control_signals` and `calculate_joint_control_signals` in the future and remove the use of default arguments in the next major versions release, as those arguments are used wholly by our downstream packages so far.

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +    traj.approach_speed_limit = locations[1].approach_speed_limit;
We should also check if `approach_speed_limit` is larger than 0.

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +    traj.approach_speed_limit = locations[1].approach_speed_limit;
`approach_speed_limit` should be check that it is larger than 0, as it looks like it is not checked further down the code path, https://github.com/open-rmf/rmf_simulation/blob/feature/speed_limits/rmf_robot_sim_common/src/utils.cpp#L32

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +        sp2.approach_speed_limit = locations[i].approach_speed_limit;
`approach_speed_limit` should be check that it is larger than 0, as it looks like it is not checked further down the code path, https://github.com/open-rmf/rmf_simulation/blob/feature/speed_limits/rmf_robot_sim_common/src/utils.cpp#L32

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +        turn_traj.approach_speed_limit = locations[i-1].approach_speed_limit;
`approach_speed_limit` should be check that it is larger than 0, as it looks like it is not checked further down the code path, https://github.com/open-rmf/rmf_simulation/blob/feature/speed_limits/rmf_robot_sim_common/src/utils.cpp#L32

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +        end_traj.approach_speed_limit = locations[i].approach_speed_limit;
`approach_speed_limit` should be check that it is larger than 0, as it looks like it is not checked further down the code path, https://github.com/open-rmf/rmf_simulation/blob/feature/speed_limits/rmf_robot_sim_common/src/utils.cpp#L32

2021-11-24 06:41 UTC, aaronchongth commented on rmf_robot_sim_common/src/slotcar_common.cpp
> +      trajectory.at(i).approach_speed_limit = msg->path[i].approach_speed_limit;
`approach_speed_limit` should be check that it is larger than 0, as it looks like it is not checked further down the code path, https://github.com/open-rmf/rmf_simulation/blob/feature/speed_limits/rmf_robot_sim_common/src/utils.cpp#L32

2021-11-24 09:18 UTC, luca-della-vedova commented
Added checks for speed limit being greater than 0 https://github.com/open-rmf/rmf_simulation/pull/56/commits/02dc918ed81380f28c2b5b2269ad5f6b8c456771.

> I also feel that we should revisit functions like `calculate_control_signals` and `calculate_joint_control_signals` in the future and remove the use of default arguments in the next major versions release, as those arguments are used wholly by our downstream packages so far.

This can be done, so the idea is that all the arguments must be specified at all times instead of relying on default arguments? In that case I think some refactoring is also in order to reduce the number of input arguments to these functions, maybe by packing more motion parameters in `struct`s

2022-04-07 01:46 UTC, luca-della-vedova commented
Closed via #71

2022-04-07 01:46 UTC, closed without merging